### ISSUE TITLE
bug in determine_reflect code

### ISSUE THREAD

**Issue by dvincentwest** [scikit-rf/scikit-rf#108]
In the skrf.calibration.determine_reflect function there is a bug on line 4017
```
    if reflect_approx is None:
        reflect_approx = reflect.copy()
        reflect_approx.s[:,0,0]=-1
```
there is no available reference to `reflect` in the function.  Currently all calling functions specify a value for `reflect_approx` so this code block is never entered.  The function should be re-written to either require an input value for reflect, or to simply require an input for reflect_approx instead of making it an optional None.

Also the docstring parameters don't match the function signature.  It may be that `reflect` is supposed to be pulled from `reflect_m`

**Comment by arsenovic** [comment]
yeah i think your interpretation is correct. the `reflect` is just used as a blank ntwk to copy info from, because immediately after copy() it's `s` parameters are set to -1. so it could be taken from any appropriate ntwk, like reflect_m, or thru_m. 

also the docstring are missing a `reflect_m`  entry.

**Comment by arsenovic** [comment]
woops. yes your guess was right vince.

**Comment by arsenovic** [comment]
you fix or me?

**Comment by dvincentwest** [comment]
Now that I understand the perspective correctly and I will include in my upcoming commits

**Comment by arsenovic** [comment]
hey vince, just closing old stuff out, is this fixed?

**Comment by dvincentwest** [comment]
Yes
