### ISSUE TITLE
Remove default measurement parameter assignment from initialization of VNA class

### ISSUE THREAD

**Issue by beuerle** [scikit-rf/scikit-rf#178]
Currently some measurement settings are applied during the initialization of
the VNA class in [line 117](https://github.com/scikit-rf/scikit-rf/blob/131771a128989b0eada0a5474cb891c4596ddd86/skrf/vi/vna/abcvna.py#L117) of `abcvna.py`. The settings are so far hard-coded in the VNA class in [line 53](https://github.com/scikit-rf/scikit-rf/blob/131771a128989b0eada0a5474cb891c4596ddd86/skrf/vi/vna/abcvna.py#L53).

Those settings should be given as function parameters during initialization, and only applied if set (or removed from `__init__` completely?).

As an addition a parameter to reset the tool when initialized (default: `False`) should be included.

```python
if kwargs['reset']:
    self.reset()
```

I can work on that, if there's a general agreement on how this should be handled. Especially taking out the assignment of the measurement parameters might be an issue for some, but could be worked around somehow.

**Comment by dvincentwest** [comment]
this is one of the embarrassing parts of the vna code.  It was kind of a hack in order to get some of the gui code I was working on to function properly.  I put in a [TODO item in networkListWidget.py](https://github.com/scikit-rf/scikit-rf/blob/131771a128989b0eada0a5474cb891c4596ddd86/qtapps/skrf_qtwidgets/networkListWidget.py#L414) to get rid of this because I agree it doesn't really belong.  I just ran into a spot at work where I wasn't able to put in much time into this at the moment.  I think it could be removed altogether or if you have a reasonable approach that makes sense, you should go for it.  Once you make those changes it will break some of the qtapps functionality, but its on me to fix that in a timely fashion.
