### ISSUE TITLE
Time domain plot is not working

### ISSUE THREAD

**Issue by BKHrf** [scikit-rf/scikit-rf#207]
I have tried your cool package and it seems to work great so far,

I have, however, some problems plotting the time domain response of my S-parameters (See attachment).
It seems that not only I have the issue, since the code on the scikit-rf website also have some issues: 
http://scikit-rf.readthedocs.io/en/v0.14.8/examples/networktheory/Time%20Domain.html

![plot_s_db_time](https://user-images.githubusercontent.com/37661070/37771688-a18de0be-2dd8-11e8-94de-4a4e8ed2cf46.PNG)

**Comment by arsenovic** [comment]
@mhuser ideas ?

i also noticed some of my time-gating  code is  working, but not producing the same results as it used to .

**Comment by mhuser** [comment]
Hum. Latest version is ok, isn't it:
http://scikit-rf.readthedocs.io/en/latest/examples/networktheory/Time%20Domain.html

**Comment by mhuser** [comment]
@BKHrf , do you use the latest version which is master on github?

**Comment by BKHrf** [comment]
I just downloaded the package through Anaconda. It states that I use 0.14.8.

**Comment by mhuser** [comment]
I am terribly sorry for this inconvenience. I understand now that we had time-domain broken in this version. There is two solution to this:
- Installing the latest version from github (way of the brave)
  `pip install git+https://github.com/scikit-rf/scikit-rf`
  (probably required to remove prior version with conda first)
- Convincing @arsenovic to bump the version on Pypi due to popular demand.

I would propose to do the second, as the time-domain may be interesting for many. What is your view @arsenovic ?

**Comment by arsenovic** [comment]
yes, your advice is good @mhuser ,

 ideally i could replace 14.8, but pypi doesnt let me replace versions for integrity reasons. i had this problem recently and had to make a bunch of wasted releases, which take a long time to test through conda-forge. 

however, here is a demo of how the plot_s_db_time() has changed from 14.5 to 14.8(actually head on master)
https://gist.github.com/arsenovic/920c9f2879d9843b7677ecb092850359
so the current version is  wrong. i am trying to trouble shoot this.  once i fix this i can make a new release.

**Comment by arsenovic** [comment]
fixed in https://github.com/scikit-rf/scikit-rf/pull/208, and subsequent prs

**Comment by mhuser** [comment]
Great!
Works good with the new release v0.14.9.

**Comment by BKHrf** [comment]
Looks great now. Thanks for the fix.
