### ISSUE TITLE
readthedocs.io not reflecting the latest API changes (v0.22.1)

### ISSUE THREAD

**Issue by denzchoe** [scikit-rf/scikit-rf#688]
As per title, 
Specifically on new deembedding Classes implemented from v0.22.1 and above

**Comment by jhillairet** [comment]
What is missing ? The documentation has been compiled and updateded 2 days ago.

**Comment by denzchoe** [comment]
The new P370 Deembedding classes are not reflected in readthedocs

<br>

![Screenshot_20220608-131005](https://user-images.githubusercontent.com/26157143/172536810-823e5df8-45c2-4727-8517-3bcf3bd13e5a.png)

**Comment by jhillairet** [comment]
Ha OK.

It is because it has not been added into the docstring header. I'll do it now.

For info, the version "0.22.1" doesn't appear as a specific version in RTD as I didn't create a specific version for this minor release. However, the ["latest"](https://scikit-rf.readthedocs.io/en/latest/) version of the doc should reflect the current master branch.

**Comment by denzchoe** [comment]
Are you holding it back to be reflected on RTD until more testing needs to be done? Or just accidental omission?

**Comment by jhillairet** [comment]
> Or just accidental omission?

Yeah, we just forgot to add them into the docstring header so sphinx did not render them...

**Comment by mhuser** [comment]
Oops, I missed to fill this docstring. Thank you very much for fixing that !

**Comment by jhillairet** [comment]
It should be ok now. Please check.

**Comment by mhuser** [comment]
Confirmation. The four IEEEP370 methods do appears now for latest version on readthedocs.
