### ISSUE TITLE
Cal kit fitting

### ISSUE THREAD

**Issue by tuxgvf** [scikit-rf/scikit-rf#749]
Hi all,
Is it possible to add a cal kit fitting tools like this one
https://www.qsl.net/in3otd/electronics/VNA_calkit/calkit.html
Thanks
Tux

**Comment by jhillairet** [comment]
Dear @tuxgvf

There is a recent page made by @biergaizi on SOLT Calibration Standards Creation : https://scikit-rf.readthedocs.io/en/latest/examples/metrology/SOLT%20Calibration%20Standards%20Creation.html 

I understand that your would like to fit some experimental S-param values to the mathematical model, am I right?

**Comment by Vinc0110** [comment]
I'm closing this issue for now. Please write and reopen this if there are open questions.

**Comment by biergaizi** [comment]
I'm not sure if this feature request should be closed. I think it's an interesting feature for inclusion on the long-term roadmap of this project. Cal kit fitting is legitimately a more difficult problem than modeling an existing kit since it involves numerical optimization. I remember seeing one example from a METAS presentation and it's not that simple. It would definitely be helpful the scikit-rf has a built-in feature to perform this task.

**Comment by tuxgvf** [comment]
I agree with biergaizi, an example of feature is this one https://www.qsl.net/in3otd/electronics/VNA_calkit/calkit.html it's an octave script. I don't know how accurate it is. But the idea is to help fitting S-parameters measurement to a polynomial model when toi have no Idea about your fringing capacitor and delay for an open for example.  It's the "reverse engineering " of this https://scikit-rf.readthedocs.io/en/latest/examples/metrology/SOLT%20Calibration%20Standards%20Creation.html .

Hope this clarify my Idea.

**Comment by biergaizi** [comment]
If anyone's still wondering about it, I've implemented a full SOL calkit fitting tool based on scikit-rf and my own documentation *SOLT Calibration Standards Creation*.

This tool is still private because it's *extremely tricky* to use properly.

Why? The fitting is non-unique, you can fit the same "Open" phase shift as a capacitance, or a transmission line delay. Likewise, one can fit a "Short" phase shift as an inductance, or a transmission line delay. It's in general impossible to distinguish both contributions without prior knowledge. Worse, the same capacitance and inductance can be fitted as a polynomial model of different degrees. High-degree polynomial fitting is sensitive to measurement noise, so a first or second-order model should be preferred. If you just want some numbers for entering into the VNA, any combination will work, as long as the fit itself is good. But problems arise when people try to compare the numbers and if they mistakenly believe the numbers are physically meaningful - they're not.

As a result, the fitting tool must have a switch or option for every possible way to fit a standard, I still need to finish the documentation before I can release it as a public tool.

I suspect adding this tool into scikit-rf will be out of scope because of the complexity involved, so it's better to approach this problem as a separate project.
